# Performs package tests on the latest versions of Ubuntu, Mac and Windows
# Uploads package to TEST PyPi.

name: TEST PyPI- Run package tests and upload to TEST PyPi

# Runs whenever a push is made to main
# Will give an error if version isn't updated in setup.py
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The workflow itself
jobs:

  # Run tests on the latest version of Ubuntu. Also update TEST PyPi.
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest

    steps:
      # Actions are found at github.com/actions
      # the "@..." refers to what version of the action to use; later = better
      - uses: actions/checkout@v2     # Check out repo under $GITHUB_WORKSPACE
      - uses: actions/setup-python@v2 # Sets up python3
        with:
          python-version: 3.9

      # Installs and upgrades pip, plus other dependencies
      # Also installs the package from setup.py
      - name: "Set up pip and dependencies, install package from setup.py"
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          # Install build deps
          python3 -m pip install setuptools wheel twine
          # If requirements.txt exists, install from it
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install the package from setup.py
          python3 setup.py install

      # Tests with unittest
      - name: Test with unittest
        run: |
          cd tests
          python3 -m unittest discover
          cd ..

      # Upload to TestPyPI
      - name: Build and Upload to TestPyPI (Linux Only)
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            python3 setup.py sdist bdist_wheel
            python3 -m twine upload dist/*
          else
            exit 1
          fi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi
